### PR TITLE
Unify session selection logic, Fixes #287

### LINKED ISSUE #287: [BUG] cannot restore session using `Autosession search`
**Describe the bug**
When opening nvim and trying to restore session using `Autosession search`, nothing happened, the session was not restored.

**To Reproduce**
1. Open nvim
2. Open a file
3. In command mode, enter `Autosession search` and select session number
4. Press enter, nothing happens.

**Expected behavior**
The expected session should be restored.

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
 sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
 - OS. e.g `uname -a`:
 Darwin K1F6JWK7KT 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64
 - Neovim version `nvim --version`
 NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
 - URL to your current config (if public)
 https://github.com/swahpy/dotfiles/blob/main/.config/nvim/lua/plugins/auto-session.lua

**Additional context**
I can delete session using `Autosession delete`.

### PR DESCRIPTION
**Pull request by cameronr**
Unify the session loading logic between Telesecop session-lens and AutoSession search so that we always use the session file to load the session (vs relying on changing directory). Set a flag to make sure cwd_change_handling (if enabled) doesn't also try to restore the session This also fixes a session load failure when a session with a git branch name is selected from Telescope session-lens or Autosession search.

Removed the non-functional (as far as I can see) code for buftypes_to_ignore. That code would not bwipeout a buffer if it matched but the buffers get wiped out by the sourcing the session file anyway and having that code generates an error when the buffer is opened in another process which interrupts the session swap. Made the option deprecated and asked anyone using it to report it on GH.

### CODE REVIEW

**Comment by cameronr** [comment]
Also fixes #314

**Comment by cameronr** [comment]
Just added a fix for #295 as well

File: lua/auto-session/init.lua [hunk 1]
```diff
@@ -479,11 +480,11 @@ function AutoSession.get_session_files()
   end
 
   local entries = vim.fn.readdir(sessions_dir, function(item)
-    return vim.fn.isdirectory(item) == 0 and not string.find(item, "x.vim$")
+    return Lib.is_session_file(sessions_dir, item)
   end)
 
   return vim.tbl_map(function(entry)
-    return { display_name = AutoSession.format_file_name(entry), path = entry }
+    return { display_name = AutoSession.format_file_name(entry), path = sessions_dir .. "/" .. entry }
```
Comment (rmagatti) [inline lua/auto-session/init.lua:487]: This might be a problem for Windows users?

**Review by rmagatti — COMMENTED** [review]
Looking good, just a comment on path joining regarding Windows users 🙏

File: lua/auto-session/init.lua (hunk 1 above)
Comment (cameronr) [reply lua/auto-session/init.lua:487]: good point. i'll update using a system agnostic separator.

**Comment by cameronr** [comment]
Should be all set now. thanks!

**Comment by tan-wei** [comment]
Is these PR will fix [this](https://github.com/rmagatti/auto-session/issues/299#issuecomment-2195881996)? Thanks very much.

**Comment by cameronr** [comment]
@tan-wei Yes, this should fix loading a git session from either `:Autosession search` or `:Telescope session-lens`. Once it's integrated, give it a shot and let us know

**Comment by tan-wei** [comment]
> @tan-wei Yes, this should fix loading a git session from either `:Autosession search` or `:Telescope session-lens`. Once it's integrated, give it a shot and let us know

Wow, great!

**Review by rmagatti — APPROVED** [review]
Looks great now, thanks again for the work put into this 🤜🤛

**Comment by tan-wei** [comment]
Great. Seems all works well now!!!
